CREATE TABLE IF NOT EXISTS tab_state (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tab_city (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  state_id INT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, state_id),
  FOREIGN KEY(state_id) REFERENCES tab_state(id)
);

CREATE TABLE IF NOT EXISTS tab_condominium (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  cnpj VARCHAR(14) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(cnpj)
);

CREATE TABLE IF NOT EXISTS tab_address (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  condominium_id INT NOT NULL,
  street VARCHAR(255) NOT NULL,
  number VARCHAR(255) NOT NULL,
  city_id INT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(condominium_id) REFERENCES tab_condominium(id) ON DELETE CASCADE,
  FOREIGN KEY(city_id) REFERENCES tab_city(id)
);