CREATE TABLE IF NOT EXISTS tab_state (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tab_city (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  state_id INT NOT NULL,
  FOREIGN KEY(state_id) REFERENCES tab_state(id)
);

CREATE TABLE IF NOT EXISTS tab_address (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  street VARCHAR(255) NOT NULL,
  number VARCHAR(255) NOT NULL,
  city_id INT NOT NULL,
  FOREIGN KEY(city_id) REFERENCES tab_state(id)
);

CREATE TABLE IF NOT EXISTS tab_condominium (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  cnpj VARCHAR(14) NOT NULL,
  address_id INT NOT NULL,
  FOREIGN KEY(address_id) REFERENCES tab_address(id)
);